<button class="btn btn-primary" id="add_custom_field">Add Custom Field</button>

<?php if(!empty($custom_fields)) : ?>
  <table id="management_table" class="table table-striped">
    <thead>
      <tr>
        <td>Field Name</td>
        <td>Field Type</td>
        <td>Is Required</td>
        <td>Operations</td>
      </tr>
    </thead>
    <tbody>
      <?php foreach($custom_fields as $custom_field) : ?>
        <?php echo Application_View::getInstance()->partial('client_custom_field_table_line.phtml',
                                                            array('custom_field'  =>  $custom_field));?>
      <?php endforeach;?>
    </tbody>
  </table>
<?php else : ?>

  <table id="management_table" class="table table-striped" style="display: none">
    <thead>
    <tr>
      <td>Field Name</td>
      <td>Field Type</td>
      <td>Is Required</td>
      <td>Operations</td>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>

  <div id="notification_no_entries" class="alert alert-info">
    <p>There are no custom fields currently created</p>
    <p>Start By Adding One</p>
  </div>

<?php endif;?>