<form method="POST" action="<?php echo isset($postUrl) ? $postUrl : '';?>">
    <?php if(isset($info['id'])) : ?>
      <input type="hidden" name="info[id]" value="<?php echo $info['id']?>"/>
    <?php endif; ?>
    <input type="hidden" name="info[flag]" value="<?php echo isset($info['flag']) ? $info['flag'] : 0;?>"/>

    <h2>Information</h2>
    <div class="control-group">
        <label class="control-label" for="first_name">First Name</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><i class="icon-user"></i></span>
                <input class="span6"
                       id="first_name"
                       name="info[first_name]"
                       type="text"
                       required="required"
                       value="<?php echo isset($info['first_name']) ? $info['first_name'] : ''?>"
                        >
            </div>
        </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="last_name">Last Name</label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-user"></i></span>
          <input class="span6"
                 id="last_name"
                 name="info[last_name]"
                 type="text"
                 required="required"
                 value="<?php echo isset($info['last_name']) ? $info['last_name'] : ''?>"
              >
        </div>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="company">Company</label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-briefcase"></i></span>
          <input class="span6"
                 id="company"
                 name="info[company]"
                 type="text"
                 value="<?php echo isset($info['company']) ? $info['company'] : ''?>"
              >
        </div>
      </div>
    </div>

    <div class="control-group">
        <label class="control-label" for="email_address">Email Address</label>
        <div class="controls">
            <div class="input-prepend">
                <span class="add-on"><i class="icon-envelope"></i></span>
                <input class="span6"
                       id="email_address"
                       name="info[email_address]"
                       type="email"
                       required="required"
                       value="<?php echo isset($info['email_address']) ? $info['email_address'] : ''?>"
                        >
            </div>
        </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="phone_number">Phone Number</label>
      <div class="controls">
        <div class="input-prepend">
          <span class="add-on"><i class="icon-book"></i></span>
          <input class="span6"
                 id="phone_number"
                 name="info[phone_number]"
                 type="text"
                 value="<?php echo isset($info['phone_number']) ? $info['phone_number'] : ''?>"
              >
        </div>
      </div>
    </div>

    <h2>Custom Information</h2>

    <?php foreach(Model_CustomFields::getInstance()->getAll() as $custom_field) : ?>
      <?php $alias = str_replace(' ', '-', $custom_field['name']);?>
      <?php if($custom_field['type'] == Model_Constant::getInstance()->client_custom_field_small) : ?>
        <div class="control-group">
          <label class="control-label" for="<?php echo $alias?>"><?php echo $custom_field['name'];?></label>
          <div class="controls">
            <div class="input-prepend">
              <span class="add-on"><i class="icon-list"></i></span>
              <input class="span3"
                     id="<?php echo $alias?>"
                     name="info[<?php echo $custom_field['name'];?>]"
                     type="text"
                     <?php echo $custom_field['is_required'] ? 'required="required"' : '';?>
                     value="<?php echo isset($info[$custom_field['name']]) ? $info[$custom_field['name']] : ''?>"
                  >
            </div>
          </div>
        </div>
      <?php elseif($custom_field['type'] == Model_Constant::getInstance()->client_custom_field_medium) : ?>
        <div class="control-group">
          <label class="control-label" for="<?php echo $alias?>"><?php echo $custom_field['name'];?></label>
          <div class="controls">
            <div class="input-prepend">
              <span class="add-on"><i class="icon-list"></i></span>
              <input class="span6"
                     id="<?php echo $alias?>"
                     name="info[<?php echo $custom_field['name'];?>]"
                     type="text"
                     <?php echo $custom_field['is_required'] ? 'required="required"' : '';?>
                     value="<?php echo isset($info[$custom_field['name']]) ? $info[$custom_field['name']] : ''?>"
                  >
            </div>
          </div>
        </div>
      <?php elseif($custom_field['type'] == Model_Constant::getInstance()->client_custom_field_large) : ?>
      <div class="control-group">
        <label class="control-label" for="<?php echo $alias?>"><?php echo $custom_field['name'];?></label>
        <textarea class="span6"
                  rows="5"
                  id="<?php echo $alias?>"
                  <?php echo $custom_field['is_required'] ? 'required="required"' : '';?>
                  name="info[<?php echo $custom_field['name'];?>]"
            ><?php echo isset($info[$custom_field['name']]) ? $info[$custom_field['name']] : ''?></textarea>
      </div>
      <?php endif;?>

    <?php endforeach;?>

    <h2>Final</h2>
    <div class="control-group">
      <label class="control-label" for="note">Personal Notes</label>
      <div class="controls span7" style="margin: 0">
          <textarea class="span7"
                    id="note"
                    name="info[note]"
              ><?php echo isset($info['note']) ? $info['note'] : ''?></textarea>
      </div>
      <div class="clear"></div>
    </div>

    <div style="margin: 0 0 0 500px;">
        <a href="index" class="btn">Cancel</a>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </div>
</form>
<div class="clear"></div>

<script type="text/javascript">
  $(document).ready(function(){
    CKEDITOR.replace('note');
  });
</script>